# Generated by Django 3.2.6 on 2021-08-24 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionAnswered',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answered_by', models.CharField(max_length=255)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('answered_by_email_id', models.EmailField(max_length=255)),
                ('form_answered', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voted_on', to='forms.form')),
            ],
        ),
        migrations.RemoveField(
            model_name='question',
            name='response',
        ),
        migrations.DeleteModel(
            name='FormAnswered',
        ),
        migrations.AddField(
            model_name='questionanswered',
            name='question_answered',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voted_on', to='forms.question'),
        ),
    ]
