# Generated by Django 3.2.6 on 2021-08-24 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0002_auto_20210824_2005'),
    ]

    operations = [
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answered_by', models.CharField(max_length=255)),
                ('response', models.CharField(max_length=500)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('answered_by_email_id', models.EmailField(max_length=255)),
                ('form_answered', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voted_on', to='forms.form')),
                ('question_answered', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voted_on', to='forms.question')),
            ],
        ),
        migrations.DeleteModel(
            name='QuestionAnswered',
        ),
    ]
